import { calculateRiskLevel } from './aiSummaryGenerator';
import { calculateHealthScore } from './healthScore';
import { generateAIInsights } from './aiInsightsEngine';

/**
 * Generate executive report as downloadable text
 */
export function generateExecutiveReport(engagements) {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const total = engagements.length;
  const active = engagements.filter(e => e.status === 'In Progress').length;
  const completed = engagements.filter(e => e.status === 'Completed').length;
  const blocked = engagements.filter(e => e.status === 'Blocked').length;
  const notStarted = engagements.filter(e => e.status === 'Not Started').length;

  const avgProgress = Math.round(engagements.reduce((s, e) => s + e.progress, 0) / total);
  const completionRate = Math.round((completed / total) * 100);

  const highRisk = engagements.filter(e => calculateRiskLevel(e) === 'High');
  const criticalHealth = engagements.filter(e => calculateHealthScore(e) < 50);

  // Workload
  const ownerCounts = {};
  engagements.filter(e => e.status === 'In Progress' || e.status === 'Blocked').forEach(e => {
    ownerCounts[e.owner] = (ownerCounts[e.owner] || 0) + 1;
  });
  const sortedOwners = Object.entries(ownerCounts).sort((a, b) => b[1] - a[1]);
  const mostLoaded = sortedOwners[0] || ['N/A', 0];
  const leastLoaded = sortedOwners[sortedOwners.length - 1] || ['N/A', 0];

  // AI Insights
  const insights = generateAIInsights(engagements);
  const highImpact = insights.filter(i => i.impact === 'High');

  let report = '';
  report += '═══════════════════════════════════════════════════════════════\n';
  report += '              RIG ENGAGEMENT TRACKER - EXECUTIVE REPORT\n';
  report += '              SAP BTP Product Management - APJ Team\n';
  report += '═══════════════════════════════════════════════════════════════\n\n';
  report += `Report Date: ${now}\n`;
  report += `Generated by: RIG Engagement Tracker AI\n\n`;

  report += '───────────────────────────────────────────────────────────────\n';
  report += '  PORTFOLIO SUMMARY\n';
  report += '───────────────────────────────────────────────────────────────\n\n';
  report += `  Total Engagements:      ${total}\n`;
  report += `  Active:                 ${active}\n`;
  report += `  Completed:              ${completed}\n`;
  report += `  Blocked:                ${blocked}\n`;
  report += `  Not Started:            ${notStarted}\n`;
  report += `  Average Progress:       ${avgProgress}%\n`;
  report += `  Completion Rate:        ${completionRate}%\n\n`;

  report += '───────────────────────────────────────────────────────────────\n';
  report += '  RISK & HEALTH OVERVIEW\n';
  report += '───────────────────────────────────────────────────────────────\n\n';
  report += `  High Risk Projects:     ${highRisk.length}\n`;
  report += `  Critical Health:        ${criticalHealth.length}\n\n`;

  if (highRisk.length > 0) {
    report += '  High Risk Engagements:\n';
    highRisk.forEach(e => {
      report += `    • ${e.customerName} (${e.status}, ${e.progress}%)\n`;
    });
    report += '\n';
  }

  report += '───────────────────────────────────────────────────────────────\n';
  report += '  TEAM CAPACITY\n';
  report += '───────────────────────────────────────────────────────────────\n\n';
  report += `  Most Loaded:            ${mostLoaded[0]} (${mostLoaded[1]} engagements)\n`;
  report += `  Least Loaded:           ${leastLoaded[0]} (${leastLoaded[1]} engagements)\n`;
  report += `  Team Size:              ${sortedOwners.length} consultants\n\n`;

  sortedOwners.forEach(([owner, count]) => {
    const bar = '█'.repeat(count) + '░'.repeat(Math.max(0, 8 - count));
    report += `    ${owner.padEnd(18)} ${bar} ${count}\n`;
  });
  report += '\n';

  report += '───────────────────────────────────────────────────────────────\n';
  report += '  AI INSIGHTS (High Impact)\n';
  report += '───────────────────────────────────────────────────────────────\n\n';
  if (highImpact.length > 0) {
    highImpact.forEach(insight => {
      report += `  ⚠ ${insight.insight}\n`;
    });
  } else {
    report += '  No high-impact issues detected.\n';
  }
  report += '\n';

  report += '───────────────────────────────────────────────────────────────\n';
  report += '  RECOMMENDATIONS\n';
  report += '───────────────────────────────────────────────────────────────\n\n';
  if (blocked > 0) report += '  1. Resolve blocked engagements through stakeholder escalation\n';
  if (highRisk.length > 0) report += '  2. Conduct risk review for all high-risk projects\n';
  if (mostLoaded[1] >= 5) report += `  3. Redistribute workload from ${mostLoaded[0]}\n`;
  report += '  4. Prioritize near-completion engagements for closure\n';
  report += '  5. Schedule quarterly portfolio review with leadership\n\n';

  report += '═══════════════════════════════════════════════════════════════\n';
  report += '                         END OF REPORT\n';
  report += '═══════════════════════════════════════════════════════════════\n';

  return report;
}

/**
 * Download text as a file
 */
export function downloadReport(content, filename) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
