import pptxgen from 'pptxgenjs';
import { calculateRiskLevel } from './aiSummaryGenerator';
import { calculateHealthScore } from './healthScore';
import { generateAIInsights } from './aiInsightsEngine';

const SAP_NAVY   = '002A86';
const SAP_BLUE   = '0070F2';
const SAP_LIGHT  = '1B90FF';
const SAP_SKY    = 'EBF5FF';
const WHITE      = 'FFFFFF';
const LIGHT_GRAY = 'F0F4FA';
const TEXT_DARK  = '1D2D44';
const TEXT_MID   = '556B82';

function computeStats(engagements) {
  const total      = engagements.length;
  const active     = engagements.filter(e => e.status === 'In Progress').length;
  const completed  = engagements.filter(e => e.status === 'Completed').length;
  const blocked    = engagements.filter(e => e.status === 'Blocked').length;
  const notStarted = engagements.filter(e => e.status === 'Not Started').length;
  const avgProgress = total > 0 ? Math.round(engagements.reduce((s, e) => s + e.progress, 0) / total) : 0;
  const completionRate = total > 0 ? Math.round((completed / total) * 100) : 0;
  const highRisk   = engagements.filter(e => calculateRiskLevel(e) === 'High');
  const criticalHealth = engagements.filter(e => calculateHealthScore(e) < 50);

  const ownerCounts = {};
  engagements.filter(e => e.status === 'In Progress' || e.status === 'Blocked').forEach(e => {
    ownerCounts[e.owner] = (ownerCounts[e.owner] || 0) + 1;
  });
  const sortedOwners = Object.entries(ownerCounts).sort((a, b) => b[1] - a[1]);

  return { total, active, completed, blocked, notStarted, avgProgress, completionRate, highRisk, criticalHealth, sortedOwners };
}

// Slide 1: Title
function addTitleSlide(prs, date) {
  const slide = prs.addSlide();
  slide.background = { color: SAP_NAVY };

  // Decorative top strip
  slide.addShape(prs.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.18, fill: { color: SAP_BLUE } });

  // Title
  slide.addText('RIG Project Tooling', {
    x: 0.6, y: 1.2, w: 8.8, h: 0.9,
    fontSize: 36, bold: true, color: WHITE, fontFace: 'Calibri',
  });

  slide.addText('Executive Report', {
    x: 0.6, y: 2.1, w: 8.8, h: 0.6,
    fontSize: 24, color: '89D1FF', fontFace: 'Calibri',
  });

  slide.addText('SAP BTP Product Management', {
    x: 0.6, y: 2.85, w: 8.8, h: 0.4,
    fontSize: 14, color: 'A0BFDF', fontFace: 'Calibri',
  });

  // Divider
  slide.addShape(prs.ShapeType.rect, { x: 0.6, y: 3.35, w: 2.5, h: 0.05, fill: { color: SAP_LIGHT } });

  slide.addText(`Report Date: ${date}`, {
    x: 0.6, y: 3.55, w: 8.8, h: 0.35,
    fontSize: 12, color: 'A0BFDF', fontFace: 'Calibri',
  });

  slide.addText('Generated by RIG Project Tooling', {
    x: 0.6, y: 3.9, w: 8.8, h: 0.35,
    fontSize: 11, color: '6A8FAF', fontFace: 'Calibri', italic: true,
  });

  // Bottom strip
  slide.addShape(prs.ShapeType.rect, { x: 0, y: 5.32, w: '100%', h: 0.18, fill: { color: SAP_BLUE } });
}

// Slide 2: Portfolio Summary
function addSummarySlide(prs, stats) {
  const slide = prs.addSlide();
  slide.background = { color: WHITE };

  // Header bar
  slide.addShape(prs.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.75, fill: { color: SAP_NAVY } });
  slide.addText('Portfolio Summary', {
    x: 0.4, y: 0.1, w: 9, h: 0.55,
    fontSize: 20, bold: true, color: WHITE, fontFace: 'Calibri',
  });

  const kpis = [
    { label: 'Total Engagements', value: stats.total,            color: SAP_NAVY },
    { label: 'Active',            value: stats.active,           color: '0070F2' },
    { label: 'Completed',        value: stats.completed,        color: '22A06B' },
    { label: 'Blocked',          value: stats.blocked,          color: 'E54646' },
    { label: 'Not Started',      value: stats.notStarted,       color: '8A9CB8' },
    { label: 'Avg Progress',     value: `${stats.avgProgress}%`, color: SAP_LIGHT },
  ];

  const cols = 3;
  const cardW = 2.8;
  const cardH = 1.4;
  const startX = 0.45;
  const startY = 1.0;
  const gapX = 0.25;
  const gapY = 0.3;

  kpis.forEach((kpi, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = startX + col * (cardW + gapX);
    const y = startY + row * (cardH + gapY);

    // Card background
    slide.addShape(prs.ShapeType.rect, { x, y, w: cardW, h: cardH, fill: { color: SAP_SKY }, line: { color: 'C8DCEF', width: 1 }, rectRadius: 0.1 });
    // Colour top accent
    slide.addShape(prs.ShapeType.rect, { x, y, w: cardW, h: 0.08, fill: { color: kpi.color }, rectRadius: 0.05 });

    slide.addText(String(kpi.value), {
      x, y: y + 0.2, w: cardW, h: 0.75,
      fontSize: 32, bold: true, color: kpi.color, align: 'center', fontFace: 'Calibri',
    });
    slide.addText(kpi.label, {
      x, y: y + 0.95, w: cardW, h: 0.35,
      fontSize: 11, color: TEXT_MID, align: 'center', fontFace: 'Calibri',
    });
  });

  // Completion rate bar
  const barY = 4.55;
  slide.addText(`Completion Rate: ${stats.completionRate}%`, {
    x: 0.45, y: barY, w: 9, h: 0.3,
    fontSize: 12, bold: true, color: TEXT_DARK, fontFace: 'Calibri',
  });
  slide.addShape(prs.ShapeType.rect, { x: 0.45, y: barY + 0.33, w: 9.1, h: 0.22, fill: { color: 'D1EFFF' }, line: { color: 'C8DCEF', width: 1 } });
  const fillW = Math.max(0.1, (stats.completionRate / 100) * 9.1);
  slide.addShape(prs.ShapeType.rect, { x: 0.45, y: barY + 0.33, w: fillW, h: 0.22, fill: { color: SAP_BLUE } });
}

// Slide 3: Risk & Health
function addRiskSlide(prs, stats) {
  const slide = prs.addSlide();
  slide.background = { color: WHITE };

  slide.addShape(prs.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.75, fill: { color: SAP_NAVY } });
  slide.addText('Risk & Health Overview', {
    x: 0.4, y: 0.1, w: 9, h: 0.55,
    fontSize: 20, bold: true, color: WHITE, fontFace: 'Calibri',
  });

  // Summary cards
  const riskCards = [
    { label: 'High Risk Projects', value: stats.highRisk.length, color: 'E54646', bg: 'FFF0F0' },
    { label: 'Critical Health',    value: stats.criticalHealth.length, color: 'E8960C', bg: 'FFF8EC' },
  ];
  riskCards.forEach((card, i) => {
    const x = 0.45 + i * 4.7;
    slide.addShape(prs.ShapeType.rect, { x, y: 1.0, w: 4.3, h: 1.2, fill: { color: card.bg }, line: { color: card.color, width: 1.5 }, rectRadius: 0.1 });
    slide.addText(String(card.value), {
      x, y: 1.05, w: 4.3, h: 0.7,
      fontSize: 36, bold: true, color: card.color, align: 'center', fontFace: 'Calibri',
    });
    slide.addText(card.label, {
      x, y: 1.75, w: 4.3, h: 0.35,
      fontSize: 12, color: TEXT_DARK, align: 'center', fontFace: 'Calibri',
    });
  });

  // High risk list
  if (stats.highRisk.length > 0) {
    slide.addText('High Risk Engagements:', {
      x: 0.45, y: 2.45, w: 9.1, h: 0.35,
      fontSize: 13, bold: true, color: TEXT_DARK, fontFace: 'Calibri',
    });
    const rows = [
      [
        { text: 'Project / Agent', options: { bold: true, color: WHITE } },
        { text: 'Company',          options: { bold: true, color: WHITE } },
        { text: 'Status',           options: { bold: true, color: WHITE } },
        { text: 'Progress',         options: { bold: true, color: WHITE } },
      ],
      ...stats.highRisk.slice(0, 6).map(e => [
        { text: e.projectName || e.customerName },
        { text: e.customerName },
        { text: e.status },
        { text: `${e.progress}%` },
      ]),
    ];
    slide.addTable(rows, {
      x: 0.45, y: 2.85, w: 9.1,
      rowH: 0.32,
      fill: { color: WHITE },
      border: { color: 'D1EFFF', width: 1 },
      fontFace: 'Calibri',
      fontSize: 10,
      color: TEXT_DARK,
      autoPage: false,
      colW: [3, 2.5, 1.8, 1.1],
      align: 'left',
      valign: 'middle',
      // Header row style applied via cell options above
    });
    // Header row background — overlay a rect
    slide.addShape(prs.ShapeType.rect, { x: 0.45, y: 2.85, w: 9.1, h: 0.32, fill: { color: SAP_NAVY } });
    // Re-add header text on top
    const headers = ['Project / Agent', 'Company', 'Status', 'Progress'];
    const colXs = [0.45, 3.45, 5.95, 7.75];
    const colWs = [3, 2.5, 1.8, 1.1];
    headers.forEach((h, i) => {
      slide.addText(h, {
        x: colXs[i] + 0.1, y: 2.87, w: colWs[i], h: 0.28,
        fontSize: 10, bold: true, color: WHITE, fontFace: 'Calibri',
      });
    });
  } else {
    slide.addText('No high risk engagements detected.', {
      x: 0.45, y: 2.6, w: 9.1, h: 0.4,
      fontSize: 12, color: '22A06B', fontFace: 'Calibri',
    });
  }
}

// Slide 4: Team Workload
function addWorkloadSlide(prs, stats) {
  const slide = prs.addSlide();
  slide.background = { color: WHITE };

  slide.addShape(prs.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.75, fill: { color: SAP_NAVY } });
  slide.addText('Team Workload', {
    x: 0.4, y: 0.1, w: 9, h: 0.55,
    fontSize: 20, bold: true, color: WHITE, fontFace: 'Calibri',
  });

  if (stats.sortedOwners.length === 0) {
    slide.addText('No active team members found.', {
      x: 0.45, y: 1.5, w: 9, h: 0.4, fontSize: 13, color: TEXT_MID, fontFace: 'Calibri',
    });
    return;
  }

  const maxCount = stats.sortedOwners[0][1];
  const barMaxW = 5.5;
  const startY = 1.05;
  const rowH = 0.48;

  stats.sortedOwners.slice(0, 8).forEach(([owner, count], i) => {
    const y = startY + i * rowH;
    const barW = maxCount > 0 ? (count / maxCount) * barMaxW : 0;

    // Owner name
    slide.addText(owner, {
      x: 0.45, y, w: 2.4, h: rowH - 0.06,
      fontSize: 11, color: TEXT_DARK, fontFace: 'Calibri', valign: 'middle',
    });
    // Bar background
    slide.addShape(prs.ShapeType.rect, { x: 2.9, y: y + 0.1, w: barMaxW, h: rowH - 0.22, fill: { color: LIGHT_GRAY } });
    // Bar fill
    if (barW > 0) {
      slide.addShape(prs.ShapeType.rect, { x: 2.9, y: y + 0.1, w: barW, h: rowH - 0.22, fill: { color: SAP_BLUE } });
    }
    // Count label
    slide.addText(String(count), {
      x: 8.6, y, w: 0.8, h: rowH - 0.06,
      fontSize: 11, bold: true, color: SAP_NAVY, fontFace: 'Calibri', valign: 'middle', align: 'center',
    });
  });

  slide.addText(`Total active consultants: ${stats.sortedOwners.length}`, {
    x: 0.45, y: 5.1, w: 9, h: 0.3,
    fontSize: 10, color: TEXT_MID, fontFace: 'Calibri', italic: true,
  });
}

// Slide 5: Insights & Recommendations
function addInsightsSlide(prs, engagements, stats) {
  const slide = prs.addSlide();
  slide.background = { color: WHITE };

  slide.addShape(prs.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.75, fill: { color: SAP_NAVY } });
  slide.addText('Insights & Recommendations', {
    x: 0.4, y: 0.1, w: 9, h: 0.55,
    fontSize: 20, bold: true, color: WHITE, fontFace: 'Calibri',
  });

  const insights = generateAIInsights(engagements).filter(i => i.impact === 'High').slice(0, 4);

  if (insights.length > 0) {
    slide.addText('Key Insights', {
      x: 0.45, y: 0.9, w: 9, h: 0.35,
      fontSize: 13, bold: true, color: TEXT_DARK, fontFace: 'Calibri',
    });
    insights.forEach((ins, i) => {
      slide.addShape(prs.ShapeType.rect, { x: 0.45, y: 1.3 + i * 0.68, w: 9.1, h: 0.55, fill: { color: 'FFF8EC' }, line: { color: 'F0C060', width: 1 }, rectRadius: 0.06 });
      slide.addText(`⚠  ${ins.insight}`, {
        x: 0.6, y: 1.33 + i * 0.68, w: 8.8, h: 0.5,
        fontSize: 10, color: '8A5700', fontFace: 'Calibri', valign: 'middle',
      });
    });
  }

  const recStartY = insights.length > 0 ? 1.3 + insights.length * 0.68 + 0.2 : 1.1;

  slide.addText('Recommendations', {
    x: 0.45, y: recStartY, w: 9, h: 0.35,
    fontSize: 13, bold: true, color: TEXT_DARK, fontFace: 'Calibri',
  });

  const recs = [];
  if (stats.blocked > 0)         recs.push('Resolve blocked engagements through stakeholder escalation');
  if (stats.highRisk.length > 0) recs.push('Conduct risk review for all high-risk projects');
  if (stats.sortedOwners[0]?.[1] >= 5) recs.push(`Redistribute workload from ${stats.sortedOwners[0][0]}`);
  recs.push('Prioritize near-completion engagements for closure');
  recs.push('Schedule quarterly portfolio review with leadership');

  recs.slice(0, 5).forEach((rec, i) => {
    slide.addText(`${i + 1}.  ${rec}`, {
      x: 0.6, y: recStartY + 0.4 + i * 0.38, w: 8.8, h: 0.35,
      fontSize: 11, color: TEXT_DARK, fontFace: 'Calibri',
      bullet: false,
    });
  });

  // Footer
  slide.addShape(prs.ShapeType.rect, { x: 0, y: 5.32, w: '100%', h: 0.18, fill: { color: SAP_BLUE } });
  slide.addText('RIG Project Tooling  |  SAP BTP Product Management', {
    x: 0, y: 5.32, w: '100%', h: 0.18,
    fontSize: 8, color: WHITE, align: 'center', fontFace: 'Calibri',
  });
}

export async function downloadPptxReport(engagements, filename) {
  const prs = new pptxgen();
  prs.layout = 'LAYOUT_WIDE';
  prs.title = 'RIG Project Tooling - Executive Report';
  prs.author = 'RIG Project Tooling';

  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const stats = computeStats(engagements);

  addTitleSlide(prs, date);
  addSummarySlide(prs, stats);
  addRiskSlide(prs, stats);
  addWorkloadSlide(prs, stats);
  addInsightsSlide(prs, engagements, stats);

  await prs.writeFile({ fileName: filename });
}
